### ISSUE TITLE
Add Header Section

### ISSUE THREAD

**Issue by mainangethe** [marshallepie/iai-fund-dev#1]
## Description

Add the header section of the landing page
This is the top part of the website.

## Properties - Desktop

- Fixed
- Translucent
- Content spaced in between
- Active section has a border-bottom
-  Border bottom on hover

## Properties - Mobile

- hamburger menu
- blue by default
-  Active: border-bottom

**Comment by mainangethe** [comment]
# Dev Comments

I was able to combine this task together with the hero section.

WIX editor is really easy to build the templates once you have the hang of it. However it does come with it's limitations.

## Issues Found with template conversion

Below are some of the drawbacks of changing the template to a WIX template: 
- You can't add border selectively on selected menu items in mobile site. Either all to have it by default or none. This affects design match [Mobile]
- You can't add smaller menu size on mobile site. Full screen / Half screen(L or R). Affects design match [Mobile]
- You can't move items to negative space on the beginning of the y-axis (top of the page) - affects the two boxes in the hero section. [All]
- You can't add gradients as CSS. Only as an image background. Affects design match of the buttons. [All]

## Device Browser Tests

Tested on:
- Desktop: Windows 10, Google Chrome Version 87.0.4280.88 (Official Build) (64-bit). Resolution 1920x1080
- Mobile: HTC Desire 10 Pro Android Version 6.0


## Screenshots

- **Desktop Preview** with Animation
https://user-images.githubusercontent.com/41260290/105461343-24632e80-5c9e-11eb-8846-492472cc048f.mp4
![01-Homepage_Section_with_animation](https://user-images.githubusercontent.com/41260290/105461737-ad7a6580-5c9e-11eb-9977-9507c9a23058.gif)

- **Mobile Preview**
![3e615a5c-0089-4149-98ec-795a23518587](https://user-images.githubusercontent.com/41260290/105462577-db13de80-5c9f-11eb-8db4-7f4cdfbf3aad.jpeg)

**Comment by marshallepie** [comment]
Great work. I’m not really worried if the design is affected by the limitations as long as the functionality is there. Thank you.

**Comment by mainangethe** [comment]
Well Noted.

Also noting them for future references to help us in evaluating pros & cons of choosing a template to use/buy if it's not already a Wix template
